### PR TITLE
[FIX] Correct iteration of rows in Relation property

### PR DESCRIPTION
**Pull request by fabarea**

### CODE REVIEW

**Comment by baschny** [comment]
@fabarea thanks for the contributions!

Is there a bug that comes from this? Doesn't the execute() return something that implements the `IteratorAggregate` and then you can use it like that in the foreach loop? 

Could you please give some more input on the error you are getting or what exactly is being solved?

**Comment by baschny** [comment]
Ah maybe that is a compatibility thing, that it used to work until TYPO3 v11 and now with TYPO3 v12 (and later) this no longer works. I think we haven't used it in any newer projects (yet). That change would then make sense (in all currently supported versions). Is that assumption right, that you are using TYPO3 v12 and it throws an exception?

**Comment by manuelselbach** [comment]
I use TYPO3 v12 and can confirm, that the current code breaks here with the following Exception, if not e.g. `->fetchAllAssociative()` is used:

```
[ TYPO3\CMS\Core\Error\Exception ]
  PHP Warning: Undefined array key 0 in /var/www/html/vendor/georgringer/faker/Classes/Property/Relation.php line 65
```

There is another issue in the `FakerCommand`. The return type is not specified, which breaks the execution after installation #26.

I fixed both here: https://github.com/manuelselbach/faker

**Comment by baschny** [comment]
Fixed in https://github.com/georgringer/faker/releases/tag/2.0.1

**Pull request merged**
